# Generated by Django 4.2.15 on 2025-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='wallet',
            name='has_made_real_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
