# Generated by Django 4.2.15 on 2025-12-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('color', models.CharField(default='#ffffff', max_length=32)),
                ('probability', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('is_high_payout', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('SPIN', 'Spin & Win'), ('PREDICT', 'Predict & Win')], max_length=16)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14)),
                ('result_label', models.CharField(max_length=64)),
                ('multiplier', models.FloatField()),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_win', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
