# Generated by Django 4.2.15 on 2025-12-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='game_type',
            field=models.CharField(choices=[('SPIN', 'Spin & Win'), ('PREDICT', 'Predict & Win'), ('PICKBOX', 'Pick a Box')], max_length=16),
        ),
    ]
