# Generated by Django 4.2.15 on 2025-12-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('SPIN', 'Spin & Win'), ('PREDICT', 'Predict & Win')], max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('auto', models.BooleanField(default=True)),
                ('margin_short', models.FloatField()),
                ('margin_long', models.FloatField()),
                ('intensity', models.FloatField()),
                ('parameters_before', models.JSONField()),
                ('parameters_after', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
