# Generated by Django 4.2.15 on 2025-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('GAME_STAKE', 'Game stake'), ('GAME_WIN', 'Game win'), ('ADJUSTMENT', 'Adjustment'), ('BONUS_CREDIT', 'Bonus credit'), ('REFERRAL_BONUS', 'Referral bonus')], max_length=20),
        ),
    ]
